---
apiVersion: v1
kind: Deployment
metadata:
  name: nginx
  labels:
    name: nginx
  template:
    spec:
      containers:
      - name: nginx
        image: nginx
        # TODO: write nginx.conf
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  ports:
  - port: 80
    name: http
  selector:
    name: nginx
  type: NodePort
